---

- hosts: all
  become: true
  tasks:

    - name: remove apache and php package
      package:
        name: 
          - "{{ apache_package }}"
          - "{{ php_package }}"
        state: absent
        update_cache: yes
