---

- hosts: all
  become: true
  tasks:
    
    - name: Update repo index
      apt:
        update_cache: yes
      when: ansible_distribution == 'Ubuntu'

    - name: remove apache 2 and php package
      apt:
        name: 
          - apache2 
          - libapache2-mod-php
        state: absent
      when: ansible_distribution == 'Ubuntu'
