---

- hosts: all
  become: true
  tasks:
    
    - name: Update repo index
      apt:
        update_cache: yes

    - name: install apache 2 package
      apt:
        name: apache2 
        state: absent

    - name: add php support for apache
      apt:
        name: libapache2-mod-php
        state: absent
