---

- hosts: all
  become: true
  tasks:

    - name: remove apache 2 and php package
      apt:
        name: 
          - apache2 
          - libapache2-mod-php
        state: absent
        update_cache: yes
      when: ansible_distribution == 'Ubuntu'
