---
- hosts: all
  become: true
  pre_tasks:
   - name: Install Updates (Oracle)
     tags: always
     dnf:
       update_only: yes
       update_cache: yes
     when: ansible_distribution == "OracleLinux"

   - name: Install Updates (Ubuntu)
     tags: always
     apt:
       upgrade: dist
       update_cache: yes
     when: ansible_distribution == "Ubuntu"

- hosts: web_server
  become: true
  tasks: 
   - name: install apache and php for Ubuntu servers
     tags: apache,apache2,Ubuntu
     apt:
       name:
         - apache2
         - libapache2-mod-php
       state: latest
     when: ansible_distribution == "Ubuntu"
 
   - name: install apache and php for OracleLinux servers
     tags: apache,httpd,OracleLinux
     dnf:
       name:
         - httpd
         - php
       state: latest
     when: ansible_distribution == "OracleLinux"
   
   - name: Copy default file for site
     tags: apache,httpd,apache2
     copy: 
       src: default_site.html
       dest: /var/www/html/index.html
       owner: root
       group: root
       mode: 0644
       
- hosts: db_server
  become: true
  tasks:
   - name: install Mariadb package (Oracle)
     tags: db, OracleLinux
     dnf: 
       name: mariadb
       state: latest
     when: ansible_distribution == "OracleLinux"

   - name: install mariadb package (Ubuntu)
     tags: db, Ubuntu
     apt:
       name: mariadb-server
       state: latest
     when: ansible_distribution == "Ubuntu"
