---
- hosts: all
  become: true
  pre_tasks:
   - name: Install Updates (Oracle)
     dnf:
       update_only: yes
       update_cache: yes
     when: ansible_distribution == "OracleLinux"

   - name: Install Updates (Oracle)
     apt:
       upgrade: dist
       update_cache: yes
     when: ansible_distribution == "Ubuntu"

- hosts: web_server
  become: true
  tasks: 
   - name: install apache and php for Ubuntu servers
     apt:
       name:
         - apache2
         - libapache2-mod-php
       state: latest
     when: ansible_distribution == "Ubuntu"
 
   - name: install apache and php for OracleLinux servers
     dnf:
       name:
         - httpd
         - php
       state: latest
     when: ansible_distribution == "OracleLinux"

- hosts: db_server
  become: true
  tasks:
   - name: install Mariadb package (Oracle)
     dnf: 
       name: mariadb
       state: latest
     when: ansible_distribution == "OracleLinux"
		
   - name: install mariadb package (Ubuntu)
     apt:
       name: mariadb-server
       state: latest
     when: ansible_distribution == "Ubuntu"
