- name: install apache and php 
  tags: apache,php,httpd
  package:
       name:
         - "{{ apache_package_name }}"
         - "{{ php_package_name }}"
       state: latest

- name: Start httpd 
  tags: apache,httpd
  service:
       name: "{{ apache_service }}"
       state: started
       enabled: yes

- name: change email address for admin
  tags: apache,httpd,OracleLinux
  lineinfile:
       path: /etc/httpd/conf/httpd.conf
       regexp: '^ServerAdmin'
       line: ServerAdmin mg@pecha.in
  when: ansible_distribution == "OracleLinux"
  notify: restart_apache
   
- name: Copy default file for site
  tags: apache,httpd,apache2
  copy: 
       src: default_site.html
       dest: /var/www/html/index.html
       owner: root
       group: root
       mode: 0644
