- name: add ssh key for simone
     tags: always
     authorized_key:
       user: simone
       key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHaveNKmhrRXJ+5C73A001olPKlCeHoYmx6Y8YfuUVOg pocadmin@master-vm-01"
